exParcial/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'wikiApp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wikiApp.urls'))
]

# DIRECCIÓN BASE: 127.0.0.1:8000/

wikiApp/urls.py
from django.urls import path, include
from . import views
app_name = 'wikiApp'



urlpatterns = [
    path('', views.principal, name='principal'),
    path('nuevoTema', views.nuevoTema, name='nuevoTema' ),
    path('nuevoArticulo', views.nuevoArticulo, name='nuevoArticulo'),
    path('articulosPorTema/<str:idTema>', views.articulosPorTema, name='articulosPorTema'),
    path('vistaArticulos/<str:idArticulo>', views.vistaArticulos, name='vistaArticulos'),
    path('resultadosBusqueda', views.resultadosBusqueda, name='resultadosBusqueda')
]

wikiApp/models.py
from django.db import models

# Create your models here.
class Tema( models.Model ):
    nombreTema = models.CharField(max_length=48, null=True, blank=True)
    descripcionTema = models.CharField(max_length=256, null=True, blank=True)

class Articulo( models.Model ):
    nombreArticulo = models.CharField(max_length=48, null=True, blank=True)
    contenidoArticulo = models.CharField(max_length=256, null=True, blank=True)
    temaRelacionado = models.ForeignKey(Tema, null=True, blank=True, on_delete=models.SET_NULL)

wikiApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Tema, Articulo
# Create your views here.


def principal(request):
    temasRegistrados = Tema.objects.all().order_by('id')
    return render(request, 'principal.html', {'temasRegistrados':temasRegistrados})

def nuevoTema(request):
    temasRegistrados = Tema.objects.all().order_by('id')
    if request.method == 'POST':
        nombreTema = request.POST.get('nombreTema')
        descripcionTema = request.POST.get('descripcionTema')
        objTema = Tema.objects.create(
            nombreTema = nombreTema,
            descripcionTema = descripcionTema
        )
        objTema.save()
        return HttpResponseRedirect( reverse('wikiApp:principal') )
    return render(request, 'nuevoTema.html', {'temasRegistrados':temasRegistrados})

def nuevoArticulo(request):
    temasRegistrados = Tema.objects.all().order_by('id')
    if request.method == 'POST':
        nombreArticulo = request.POST.get('nombreArticulo')
        temaSeleccionado = request.POST.get('temaSeleccionado')
        contenidoArticulo = request.POST.get('contenidoArticulo')
        temaRelacionado = Tema.objects.get(id=temaSeleccionado)

        objArticulo = Articulo.objects.create(
            nombreArticulo = nombreArticulo,
            contenidoArticulo = contenidoArticulo,
            temaRelacionado=temaRelacionado
        )
        objArticulo.save()

        return HttpResponseRedirect( reverse('wikiApp:principal') )
    return render(request, 'nuevoArticulo.html', {'temasRegistrados':temasRegistrados})

def articulosPorTema(request, idTema):
    temasRegistrados = Tema.objects.all().order_by('id')
    objTema = Tema.objects.get(id=idTema)
    listaArticulos = objTema.articulo_set.all()

    return render(request, 'articulosPorTema.html',{
        'temasRegistrados': temasRegistrados,
        'objTema':objTema,
        'listaArticulos':listaArticulos
    })

def vistaArticulos(request, idArticulo):
    temasRegistrados = Tema.objects.all().order_by('id')
    objArticulo = Articulo.objects.get(id=idArticulo)

    return render(request, 'vistaArticulos.html', {
        'temasRegistrados':temasRegistrados,
        'objArticulo':objArticulo})

def resultadosBusqueda(request):
    temasRegistrados = Tema.objects.all().order_by('id')
    articuloBuscado = request.POST.get('buscarArticulo')
    articuloEncontrado = Articulo.objects.filter(nombreArticulo__contains=articuloBuscado)
    return render(request, 'resultadosBusqueda.html', {
        'temasRegistrados': temasRegistrados,
        'articuloEncontrado':articuloEncontrado})

# artículos por tema
# artículos
# búsqueda:

wikiApp/templates/articulosPorTema.html
{% extends "layout.html" %}

{% block title %}
    {{ objTema.nombreTema }}
{% endblock %}

{% block contenido %}
    <br>
    <div class="h1 bg-warning"> {{ objTema.nombreTema }} </div>
    <br>
    <div class="h3">
        <ul>
        {% for articulo in listaArticulos %}
            <li> <a href="{% url 'wikiApp:vistaArticulos' articulo.id %}">{{ articulo.nombreArticulo }}</a> </li>
            <br>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

wikiApp/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
        <div class="row px-4">
            <div class="col-3"> <!-- SECCIÓN IZQUIERDA -->
                <br>
                <div class="h3 bg-warning"> DIRECTORIO </div>
                <br>
                <!--  barra de búsqueda   -->
                <div>
                <form class="row" method="post" action="{% url 'wikiApp:resultadosBusqueda' %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <div class="form-outline" data-mdb-input-init>
                            <input type="search" id="form1" class="form-control fs-4" name="buscarArticulo" required/>
                            <label class="form-label fs-4" for="form1">Buscar</label>
                        </div>
                        <div>
                            <button type="submit" class="btn btn-primary fs-4" data-mdb-ripple-init>
                            <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
                </div>
                <!--  barra de búsqueda   -->
                <br>
                <!-- botón de inicio -->
                    <div class="col-5">
                        <button type="button" class="btn btn-primary"><a class="link-light fs-5" href="{% url 'wikiApp:principal' %}">Inicio</a></button>
                    </div>
                <!-- botón de inicio -->
                <br>
                <!--  lista de artículos   -->
                <div>
                    <div class="h3 bg-warning">TEMAS DISPONIBLES</div>
                    <ul>
                        {% for tema in temasRegistrados %}
                            <li><a class="fs-4" href="{% url 'wikiApp:articulosPorTema' tema.id %}">{{ tema.nombreTema }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!--  botones de creación  -->
                <div class="row justify-content-around">
                    <div class="col-6">
                        <button type="button" class="btn btn-primary"><a class="link-light fs-5" href="{% url 'wikiApp:nuevoTema' %}">Crear nuevo tema</a></button>
                    </div>
                    <div class="col-6">
                        <button type="button" class="btn btn-primary"><a class="link-light fs-5" href="{% url 'wikiApp:nuevoArticulo' %}">Crear nuevo artículo</a></button>
                    </div>
                </div>
            </div>
            <div class="px-4 col-8"> <!-- SECCIÓN DERECHA -->
                {% block contenido %}
                {% endblock %}
            </div>
        </div>
</body>
</html>

wikiApp/templates/nuevoArticulo.html
{% extends "layout.html" %}

{% block title %}
    NUEVO ARTIÍCULO
{% endblock %}

{% block contenido %}
    <br>
    <div class="h1 bg-warning">CREAR NUEVO ARTÍCULO</div>
    <br>
    <form class="row fs-4" method="post" action="{% url 'wikiApp:nuevoArticulo' %}">
        {% csrf_token %}
        <div class="form-group py-3">
            <label for="nombreArticuloInput">Ingrese el título del artículo</label>
            <input type="text" class="form-control fs-4" name="nombreArticulo" id="nombreArticuloInput">
        </div>

        <div class="form-group py-3">
            <label for="temaSeleccionadoInput">Seleccione Tema</label>
            <select  class="form-select fs-4" name="temaSeleccionado" id="temaSeleccionadoInput" required>
                <option value="" selected></option>
                {% for temaInfo in temasRegistrados %}
                <option value="{{ temaInfo.id }}">{{ temaInfo.nombreTema }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group py-3">
            <label for="contenidoArticuloInput">Ingrese el contenido del artículo</label>
            <input type="text" class="form-control fs-4" name="contenidoArticulo" id="contenidoArticuloInput">
        </div>
        <div class="form-group py-2">
            <input type="submit" value="REGISTRAR">
        </div>
    </form>
{% endblock %}

wikiApp/templates/nuevoTema.html
{% extends "layout.html" %}

{% block title %}
    NUEVO TEMA
{% endblock %}

{% block contenido %}
    <br>
    <div class="h1 bg-warning">CREAR NUEVO TEMA</div>
    <br>
    <div>
    <form class="fs-4" method="post" action="{% url 'wikiApp:nuevoTema' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="nombreTemaInput">Ingrear título del tema</label>
            <input type="text" class="form-control fs-4" name="nombreTema" id="nombreTemaInput" >
        </div>
        <br>
        <div class="form-group">
            <label for="descripcionTemaInput">Ingrese descripción</label>
            <input type="text" class="form-control fs-4" name="descripcionTema" id="descripcionTemaInput">
        </div>
        <br>
        <div>
            <input type="submit" value="REGISTRAR">
        </div>
    </form>
    </div>
{% endblock %}

wikiApp/templates/principal.html
{% extends "layout.html" %}

{% block title %}
    DIRECTORIO
{% endblock %}

wikiApp/templates/resultadosBusqueda.html
{% extends "layout.html" %}

{% block title %}
    RESULTADOS DE BÚSQUEDA
{% endblock %}

    {% block contenido %}
    <br>
    <div class="h1 bg-warning">RESULTADOS DE BÚSQUEDA</div>
    <br>
    <div class="h3">
        <ul>
        {% for articulo in articuloEncontrado %}
            <li> <a href="{% url 'wikiApp:vistaArticulos' articulo.id %}">{{ articulo.nombreArticulo }}</a> </li>
            <br>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

wikiApp/templates/vistaArticulos.html
{% extends "layout.html" %}

{% block title %}
    {{ objArticulo.nombreArticulo }}
{% endblock %}

{% block contenido %}
    <div>
        <br>
        <div class="h3 bg-warning">{{ objArticulo.temaRelacionado.nombreTema }}</div>
        <br>
        <div class="h1 col-9">
            {{ objArticulo.nombreArticulo }}
        </div>
        <br>
        <div class="col-7">
            <p class="lh-sm fs-4"> {{ objArticulo.contenidoArticulo }} </p>
        </div>

    </div>
{% endblock %}